version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresDB 
    restart: always
    environment:
    - POSTGRES_USER=artemkashipov
    - POSTGRES_PASSWORD=$POSTGRES_PWD
    - POSTGRES_DB=l0_data
    ports:
    - '5432:5432'
    volumes:
    - postgres_db:/Users/artemkashipov/Documents/data

volumes:
  postgres_db:
    driver: local
